### ISSUE TITLE
Can't convert an INT to lower()

### ISSUE THREAD

**Issue by mixographer** [aziezahmed/podcast-player#5]
in the menu i select a podcast by number, and get: 

Traceback (most recent call last):
  File "/usr/local/bin/podcast", line 9, in <module>
    load_entry_point('podcast-player==1.4.0', 'console_scripts', 'podcast')()
  File "/Library/Python/2.7/site-packages/podcast_player/cli.py", line 286, in main
    podcast_menu()
  File "/Library/Python/2.7/site-packages/podcast_player/cli.py", line 246, in podcast_menu
    choice = handle_choice()
  File "/Library/Python/2.7/site-packages/podcast_player/cli.py", line 126, in handle_choice
    choice = choice.lower()

**Comment by mixographer** [comment]
It looks like python3 is required and I accidentally used 2.7.
